---
- name: Base services and configs on all nodes
  hosts: all
  sudo: true
  gather_facts: true
  #vars:
    #PRIVATE_INTERFACE: eth1
    #PUBLIC_INTERFACE: eth3
  vars_files:
    - vars/main.yaml
  remote_user: vagrant
  tasks:

    #- name: install ssh key
    #  authorized_key: user=vagrant
    #                  key= "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}" 
    #                  state=present

    - name: Network Interface Configuration
      template: src=templates/etc/network/interfaces.d/public.j2 dest=/etc/network/interfaces.d/{{ PUB_INT }}.cfg owner=root group=root
      register: needRestartNW
      when: ansible_hostname == "network"

    - name: Restart Networking service
      service: name=networking state=restarted
      when: ansible_hostname == "network" and needRestartNW|changed

    - name: Configure Name Resolution
      copy: src=files/etc/hosts dest=/etc/hosts owner=root group=root

    - name: Update Apt Cache
      apt: 
        update-cache: yes

    - name: Install Chrony - NTP service, sw-properties for add-apt-repo
      apt:
        pkg: "{{ item }}"
        state: latest
        update-cache: yes
        cache_valid_time: 600
      with_items:
        - chrony
        - software-properties-common
        - python-software-properties
      register: Installs_Chrony_RepoCapab

    - name: Stop chrony server
      service:
        name: chrony
        state: stopped
      when: Installs_Chrony_RepoCapab.results[0]|changed


    - set_fact: NTP_SERVER="pool.ntp.org"
      when: ansible_hostname == "controller" and Installs_Chrony_RepoCapab.results[0]|changed
    - set_fact: NTP_SERVER="controller"
      when: ansible_hostname != "controller" and Installs_Chrony_RepoCapab.results[0]|changed
    - include: chronyConf.yaml
      when: Installs_Chrony_RepoCapab.results[0]|changed


#    - set_fact: NTP_SERVER="controller"
#      when: ansible_hostname != "controller" and Installs_Chrony_RepoCapab.results[0]|changed
#    - include: chronyConf.yaml
#      when: ansible_hostname != "controller" and Installs_Chrony_RepoCapab.results[0]|changed

    - name: Start chrony server
      service:
        name: chrony
        state: started
        enabled: yes
      when: Installs_Chrony_RepoCapab.results[0]|changed


    - apt_repository:
        repo="deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/liberty main" 
        state=present

    - name: Upgrade Distribution
      apt:
        update-cache: yes
        upgrade: full
        force: yes
      ignore_errors: True
      async: 600
      poll: 10

    - name: Remove unnecessary packages
      command: apt-get -y autoremove

    - name: Check if reboot is required
      register: file
      stat: path=/var/run/reboot-required get_md5=no

    - include: reboot.yaml
      when: file.stat.exists == true

    - name: Install Openstack Client
      apt:
        force: yes
        pkg: "{{ item }}"
        state: latest
        update-cache: yes
        cache_valid_time: 600
      with_items:
        - python-openstackclient
