---
- name: Message broker on controller
  hosts: controller
  sudo: true
  gather_facts: true
  remote_user: vagrant
  tasks:
    - name: Install Rabbit Message Queue Server
      apt:
        pkg: "{{ item }}"
        state: latest
        force: yes
        update-cache: yes
        cache_valid_time: 600
      with_items:
        - rabbitmq-server
