- name: Reboot host
  command: /sbin/reboot removes=/var/run/reboot-required

- name: Wait for host to complete reboot
  sudo: False
  delegate_to: localhost
  wait_for:
    host: "{{ ansible_ssh_host|default(inventory_host) }}"
    port: "{{ ansible_ssh_port|default(22) }}"
    delay: 30
    timeout: 300
    state: started

