---
- hosts: all
  sudo: yes
  gather_facts: yes
  remote_user: vagrant
  vars:
    PRIVATE_INTERFACE: eth1
    PUBLIC_INTERFACE: eth2
  tasks:

    #- name: install ssh key
    #  authorized_key: user=vagrant
    #                  key= "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}" 
    #                  state=present

#    - name: Network Interface Configuration
#      template: src=etcNetworkInterfaces.j2 dest=/etc/network/interfaces owner=root group=root

    - name: Configure Name Resolution
      copy: src=etcHosts dest=/etc/hosts owner=root group=root

    - name: Install Chrony - NTP service
      apt: pkg=chrony state=installed update_cache=true

    - name: Install add-app-repo capability
      apt: pkg=software-properties-common state=installed update_cache=false
      register: addRepoCapable

    - apt_repository: repo="deb http://ubuntu-cloud.archive.canonical.com/ubuntu trusty-updates/liberty main" state=present

    - name: Upgrade Distribution
      #when: openstackRepo|success
      apt: update_cache=true upgrade=dist
      register: upgradeState # Reboot if upgraded

    - name: Install Openstack Client
      apt: pkg=python-openstackclient state=installed update_cache=false
      register: openstackInstallState

- hosts: controller
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  tasks:
    - lineinfile: dest=/etc/chrony/chrony.conf
                  line='server 0.pool.ntp.org iburst'
      notify:
        - Reload chrony

    - name: Install MariaDB and Python-pyMySQL
      apt: pkg= "{{ item }}" state=installed update_cache=false
      with_items: 
      - python-pymysql
      - mariadb-server

  handlers:
    - name: Reload chrony
      service: name=chrony state=reloaded

- hosts: all:!controller
  sudo: yes
  gather_facts: no
  remote_user: vagrant
  tasks:
    - lineinfile: dest=/etc/chrony/chrony.conf
                  line='server controller iburst'
      notify:
        - Reload chrony
  handlers:
    - name: Reload chrony
      service: name=chrony state=reloaded
